name: library_app
description: "A new Flutter project."

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter
  firebase_auth: ^5.4.2
  google_sign_in: ^5.4.2
  firebase_core: ^3.11.0
  get: ^4.6.6
  cloud_firestore: ^5.6.3
  crypto: ^3.0.3

  cupertino_icons: ^1.0.8
  agora_rtc_engine: ^6.5.0
  permission_handler: ^11.3.1
  http: ^1.2.2


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

